import "./globals.css";
import  "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./_components/Navbar/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container-fluid p-0">
        <Navbar />
        {children}

      </body>
    </html>
  );
}
