import "./globals.css";
import  "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "./_components/BoostrapClient";
import NavbarComponent from "./_components/Navbar";
import Footer from "./_components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container-fluid p-0">
        <NavbarComponent />
        {children}
        <Footer />
        <BootstrapClient />
      </body>
    </html>
  );
}
